sudo: required
services:
  - docker

before_install: 
  - docker build -t nsfa/docker-react -f Dockerfile.dev .

script: 
  - docker run -e CI=true nsfa/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "Ahmad-docker"
  env: "Ahmad-docker-env"
  bucket_name: "$BUCKET_NAME"
  bucket_path: "Ahmad-docker"
  on:
    branch: mastar
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
  